list: $/itrail/youtubeplaylist/models/block/columns.yaml
modelClass: Itrail\YouTubePlayList\Models\Block
title: Blocks
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'itrail/youtubeplaylist/blocks/update/:id'
